remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: A Real-Time Lyrics Alignment System Using Chroma and Phonetic Features for Classical Singing Performance
tagline: Jiyun Park, Taegyun Kwon, Sangeon Yong, and Juhan Nam
show_downloads: false
author:
  name: Jiyun Park
  url: https://laurenceyoon.github.io
